### ISSUE TITLE
Map doesn't work but the API seems to

### ISSUE THREAD

**Issue by canales** [bubastis/ocorrencias-lx#1]
Hi, it seems like the map stopped working but the API still seems to be fetching data, though from an older date (2021). Are you still able to pull in the data from the CML's database or what could be the problem?

thanks

**Comment by bubastis** [comment]
Thank you for the comment!

Yes, it is down, I think CML changed its databasing system. I was able to copy what existed (millions of events) to carto. I’ve been thinking of working on it but I had a lot of problems since 2021! Will try to do that soon.

**Comment by canales** [comment]
Not sure if you saw but the CML published an open dataset of the ocurrencias, though with very limited details about each of the reports of their resolution. It's probably not helpful for this map, but just sharing in any case (I'd with the CML would share the actual resolution of these reports and their outcome, but I doubt that will happen any time soon). https://lisboaaberta.cm-lisboa.pt/index.php/pt/dados/conjuntos-de-dados

**Comment by bubastis** [comment]
Are you talking about their “Na minha Rua” database? It seems separated by years and not updated in real time!

**Comment by canales** [comment]
Yeah that one, but it definitely looks like not in real time and stripped out of almost all type of relevant info. For the access to the real-time database, where you using the API below? It seems like it now requires authen credentials to access it (I think in the past I remember seeing it without any access restrictions). 

url = "https://gisapps.cm-lisboa.pt/arcgisapps/rest/services/GOPI_Maps_Secure/NaMinhaRuaRead_PROD/MapServer/0/query?where=1%3D1&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=id%2Cnumero%2Crequerente%2Cemail%2Clocal%2Creferencia%2Cdescricao%2Ctipo%2Carea%2Cfreg_descricao%2Cstate&returnGeometry=true&returnTrueCurves=false&maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false&returnCountOnly=false&orderByFields=id+DESC&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&returnDistinctValues=false&resultOffset=&resultRecordCount=1000&f=geojson"

**Comment by canales** [comment]
From doing a bit of research about the API's that the website "https://naminharualx.cm-lisboa.pt/gopiv2/naminharua/index.jsp" uses I found that they also connect to similar API's to the one you use, but they append this at the beginning "https://naminharualx.cm-lisboa.pt/gopiv2/proxy.jsp?" to bypass the token.

I tried the following url and it worked: https://naminharualx.cm-lisboa.pt/gopiv2/proxy.jsp?https://gisapps.cm-lisboa.pt/arcgisapps/rest/services/GOPI_Maps_Secure/NaMinhaRuaRead_PROD/MapServer/0/query?where=1%3D1&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=id%2Cnumero%2Crequerente%2Cemail%2Clocal%2Creferencia%2Cdescricao%2Ctipo%2Carea%2Cfreg_descricao%2Cstate&returnGeometry=true&returnTrueCurves=false&maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false&returnCountOnly=false&orderByFields=id+DESC&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&returnDistinctValues=false&resultOffset=&resultRecordCount=1000&f=geojson

**Comment by bubastis** [comment]
Thank you immensely!

I had to relearn how to operate with Netlify, and they are now finally working!

https://ocorrencias-lx.netlify.app/
https://ocorrencias-lx-mapa.netlify.app/

I look at the now with new opinions on how they should be. I already had some at the time but I wasn’t able to be a 150% code player.

Best,
João

**Comment by canales** [comment]
Fantastic, glad that helped!
